#!/bin/bash

usage="Usage: $(basename $0) [-dh] filename\n
        -d              delete the (temporary) header file\n
        -h              display help (this screen)\n\n
        example:        "$(basename $0)" -d main\n
        notice the filename without extension!"

errmsg="You have to specify a file!"

MYPWD=${PWD}

dswitch=false
hswitch=false
exitcode=0

while getopts "dh" option; do
 case $option in
  d)
   dswitch=true
   ;;
  h)
   hswitch=true
   ;;
  \?)
   echo "invalid option -$OPTARG"
   hswitch=true
   exitcode=1
 esac
done

shift $((OPTIND - 1))
filename="$1"

if [ "$hswitch" = true ]; then
        echo -e $usage
        exit $exitcode
fi

if [ -e "$filename.asm" ]; then
    nasm -f elf64 -o "$MYPWD/$1.o" "$MYPWD/$1.asm";
    ld -o "$MYPWD/$1" "$MYPWD/$1.o";
fi
