#!/bin/bash

usage="Usage: $(basename $0) [-dnh] filename\n
        -d		delete the (temporary) header file\n
        -n		don't put '32' at end of program name\n
        -h		display help (this screen)\n\n
        example:	"$(basename $0)" -d main\n
	notice the filename without extension!"

errmsg="You have to specify a file!"

MYPWD=${PWD}

dswitch=false
nswitch=false
hswitch=false
exitcode=0

while getopts "dnh" option; do
 case $option in
  d)
   dswitch=true
   ;;
  n)
   nswitch=true
   ;;
  h)
   hswitch=true
   ;;
  \?)
   echo "invalid option -$OPTARG"
   hswitch=true
   exitcode=1
 esac
done

shift $((OPTIND - 1))
filename="$1"

if [ "$hswitch" = true ]; then
	echo -e $usage
	exit $exitcode
fi

if [ -e "$filename.asm" ]; then
	nasm -f elf -o "$MYPWD/$filename.o" "$MYPWD/$filename.asm";
	if [ '$1 | grep -o ..$' == '32' ] || [ "$nswitch" = true ]; then
        ld -m elf_i386 -o "$MYPWD/$filename" "$MYPWD/$filename.o";
    else
        ld -m elf_i386 -o "$MYPWD/$filename"32 "$MYPWD/$filename.o";
    fi
fi

if [ "$dswitch" = true ]; then
	rm -rf "$MYPWD/$filename.o";
fi